import {chromium} from '/tmp/spare-browser/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
const origin=process.env.SPARE_E2E_ORIGIN||'https://pledge.pauravhp.com';
const browser=await chromium.launch({headless:true,args:['--no-sandbox',...(process.env.SPARE_E2E_EDGE_IP?[`--host-resolver-rules=MAP ${new URL(origin).hostname} ${process.env.SPARE_E2E_EDGE_IP}`]:[])]});const c=await browser.newContext({viewport:{width:390,height:844}});const qa=await c.newPage();
const result={backend:origin,storage:'isolated service; durable SQLite WAL with synchronous FULL',checks:[],stripe_test_paid:false};mkdirSync('test-results',{recursive:true});
async function api(path,data){const x=await qa.evaluate(async({path,data})=>{const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});return{status:r.status,data:await r.json()};},{path,data});assert.equal(x.status,200,x.data.error||`HTTP ${x.status}`);return x.data;}
try{
 await qa.goto(origin);await qa.getByRole('button',{name:/Yes, add/}).waitFor();const state=await api('/api/state');assert.equal(state.pending_cents,0);result.checks.push('Public phone UI and hosted account storage respond');
 const q=await api('/api/quote',{provider:'OpenRouter',usd_total:'10.80',purchase_key:crypto.randomUUID()});assert.equal(q.source,'estimated');assert.equal(q.gift_cents,23);result.checks.push('Hosted FX estimate matches the live merchant quote');
 const exact=await api('/api/quote',{provider:'Demo',cad_total:'29.85',purchase_key:crypto.randomUUID()});assert.equal(exact.gift_cents,15);
 await api('/api/demo/near-threshold',{run_id:crypto.randomUUID()});const top=await api('/api/quote',{provider:'Demo',cad_total:'32.33',purchase_key:crypto.randomUUID()});const pledges=await Promise.all(Array.from({length:5},()=>api('/api/pledge',{quote_id:top.id})));assert.ok(pledges.every(x=>x.pending_cents===536));result.checks.push('Concurrent Yes requests create one hosted pledge');
 if(process.env.SPARE_E2E_RESTART==='1'){
  execFileSync('systemctl',['--user','restart','spare-cad-demo.service']);let restored;for(let i=0;i<30;i++){try{restored=await api('/api/state');break;}catch{await qa.waitForTimeout(250);}}assert.equal(restored?.pending_cents,536);result.checks.push('Actual service restart preserves all pending pledges');
 }
 const first=await api('/api/checkout',{});const repeated=await api('/api/checkout',{});assert.equal(first.id,repeated.id);assert.equal(first.amount_cents,536);result.checks.push('Repeated hosted checkout requests reuse one reservation and Stripe session');
 const p=await c.newPage();await p.goto(first.url);await p.locator('#email').waitFor();
 const back=p.locator('a[href*="?cancel="]:visible');if(await back.count()===1)await back.click();else await p.goto(origin+'/?cancel='+first.id);
 await p.getByRole('button',{name:'Yes, continue to Stripe',exact:true}).waitFor();const cancelled=await api('/api/state');assert.equal(cancelled.pending_cents,536);assert.equal(cancelled.active,null);assert.equal(cancelled.paid_cents,0);result.checks.push('Cancellation return expires the Stripe session and preserves every unpaid pledge');
 await p.getByRole('button',{name:'Yes, continue to Stripe',exact:true}).click();await p.waitForURL('https://checkout.stripe.com/**');const active=(await api('/api/state')).active;assert.notEqual(active.id,first.id);
 await p.locator('#email').fill('spare-hosted-e2e@example.com');await p.locator('#cardNumber').fill('4242424242424242');await p.locator('#cardExpiry').fill('12/30');await p.locator('#cardCvc').fill('123');if(await p.locator('#billingName:visible').count())await p.locator('#billingName').fill('Spare Sandbox Test');if(await p.locator('#billingCountry:visible').count())await p.locator('#billingCountry').selectOption('CA');if(await p.locator('#billingPostalCode:visible').count())await p.locator('#billingPostalCode').fill('V6B 1A1');
 await p.locator('button[type="submit"]:visible').click();await p.waitForURL(origin+'/**',{timeout:60000});await p.getByText('A little extra.',{exact:false}).waitFor({timeout:20000});
 const paid=await api('/api/checkout/status?id='+active.id);assert.equal(paid.status,'paid');assert.equal(paid.pending_cents,0);assert.equal(paid.paid_cents,536);assert.equal((await api('/api/checkout/status?id='+active.id)).paid_cents,536);result.stripe_test_paid=true;result.amount_cents=536;result.currency='CAD';result.checks.push('Public server verifies CAD5.36 sandbox payment; replay cannot double-clear');await p.screenshot({path:'test-results/hosted-mobile-paid.png',fullPage:true});
 await p.reload();await p.getByRole('button',{name:/Yes, add/}).waitFor();assert.equal((await api('/api/state')).paid_cents,536);result.checks.push('Reload preserves the verified paid balance');
 const other=await browser.newContext({viewport:{width:390,height:844}});const o=await other.newPage();await o.goto(origin);await o.getByRole('button',{name:/Yes, add/}).waitFor();const isolation=await o.evaluate(async id=>{const s=await fetch('/api/state').then(r=>r.json());const r=await fetch('/api/checkout/status?id='+id);return{state:s,status:r.status};},active.id);assert.equal(isolation.state.paid_cents,0);assert.equal(isolation.status,404);result.checks.push('Another browser account cannot read this checkout or balance');await other.close();
}catch(e){result.failure=e.message;process.exitCode=1;}
finally{await browser.close();writeFileSync('test-results/hosted-e2e.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));}
