import test from 'node:test';import assert from 'node:assert/strict';
import worker,{verifySession,hash} from '../worker/index.js';import {SQLiteD1} from '../scripts/sqlite-adapter.mjs';import {Ledger} from '../worker/ledger.js';
function environment(){const DB=new SQLiteD1();DB.migrate();return{DB,TEST_FX:'1.4246',STRIPE_API_KEY:'rk_test_fake',APP_ORIGIN:'https://spare.test'};}
async function call(env,path,data,cookie){const headers={};if(data){headers['Content-Type']='application/json';headers.Origin='https://spare.test';}if(cookie)headers.Cookie=cookie;const r=await worker.fetch(new Request(`https://spare.test${path}`,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
test('quote, pledge, replay, manual correction, and private-account isolation',async()=>{const env=environment();const a=await call(env,'/api/state');const b=await call(env,'/api/state');const q=await call(env,'/api/quote',{provider:'OpenRouter',usd_total:'22.40',purchase_key:'test-purchase'},a.cookie);assert.equal(q.status,200);assert.equal(q.data.source,'estimated');assert.equal(q.data.cad_cents,3271);const p=await call(env,'/api/pledge',{quote_id:q.data.id},a.cookie);assert.equal(p.data.pending_cents,29);const replay=await call(env,'/api/pledge',{quote_id:q.data.id},a.cookie);assert.equal(replay.data.created,false);assert.equal((await call(env,'/api/pledge',{quote_id:q.data.id},b.cookie)).status,409);assert.equal((await call(env,'/api/state',null,b.cookie)).data.pending_cents,0);const manual=await call(env,'/api/quote',{provider:'OpenRouter',cad_total:'29.99',purchase_key:'manual-purchase'},a.cookie);assert.equal(manual.data.gift_cents,101);env.DB.close();});
test('forged redirects do not settle; wrong origin cannot pledge',async()=>{const env=environment();const a=await call(env,'/api/state');const fake=await call(env,'/api/checkout/status?id=forged',null,a.cookie);assert.equal(fake.status,404);const r=await worker.fetch(new Request('https://spare.test/api/pledge',{method:'POST',headers:{Cookie:a.cookie,'Content-Type':'application/json',Origin:'https://evil.test'},body:'{"quote_id":"fake"}'}),env);assert.equal(r.status,403);env.DB.close();});
test('one-time extension pairing cannot be replayed',async()=>{const env=environment();const a=await call(env,'/api/state');const code=(await call(env,'/api/pair/code',{},a.cookie)).data.code;const device=await call(env,'/api/pair/redeem',{code});assert.equal(device.status,200);assert.equal((await call(env,'/api/pair/redeem',{code})).status,409);const r=await worker.fetch(new Request('https://spare.test/api/state',{headers:{Authorization:`Bearer ${device.data.token}`}}),env);assert.equal(r.status,200);assert.equal(env.DB.db.prepare('SELECT COUNT(*) n FROM devices').get().n,1);env.DB.close();});
test('payment validation rejects wrong CAD amounts and unpaid sessions',async()=>{const env=environment();env.DB.db.prepare("INSERT INTO users(id,customer_id,created_at) VALUES('u','cus_test',1)").run();const ledger=new Ledger(env.DB);const checkout={id:'c',user_id:'u',amount_cents:500,stripe_session_id:'cs_test',status:'open'};let s={livemode:false,currency:'cad',amount_total:501,customer:'cus_test',metadata:{spare_checkout_id:'c'},status:'complete',payment_status:'paid',payment_intent:{status:'succeeded',amount_received:501,currency:'cad'}};env.STRIPE_FETCH=async()=>Response.json(s);await assert.rejects(verifySession(env,ledger,checkout),/did not match/);s={...s,amount_total:500,payment_status:'unpaid',status:'open'};assert.equal((await verifySession(env,ledger,checkout)).status,'open');env.DB.close();});
test('unsigned or stale webhook events cannot clear pledges',async()=>{const env=environment();env.STRIPE_WEBHOOK_SECRET='whsec_test';const r=await worker.fetch(new Request('https://spare.test/api/webhook',{method:'POST',headers:{'stripe-signature':'t=1,v1='+'0'.repeat(64)},body:'{}'}),env);assert.equal(r.status,400);env.DB.close();});

test('disconnect revokes the device token without changing its pledges',async()=>{const env=environment();const a=await call(env,'/api/state');const q=await call(env,'/api/quote',{provider:'OpenRouter',cad_total:'29.85',purchase_key:'revoke-test'},a.cookie);await call(env,'/api/pledge',{quote_id:q.data.id},a.cookie);const code=(await call(env,'/api/pair/code',{},a.cookie)).data.code;const d=await call(env,'/api/pair/redeem',{code});const headers={Authorization:`Bearer ${d.data.token}`,'Content-Type':'application/json'};const r=await worker.fetch(new Request('https://spare.test/api/device/revoke',{method:'POST',headers,body:'{}'}),env);assert.equal(r.status,200);assert.equal((await worker.fetch(new Request('https://spare.test/api/state',{headers}),env)).status,401);assert.equal((await call(env,'/api/state',null,a.cookie)).data.pending_cents,15);env.DB.close();});
