import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { SQLiteD1 } from '../scripts/sqlite-adapter.mjs';
import { Ledger } from '../worker/ledger.js';
import { cents,roundUp,convertUSD } from '../worker/money.js';
function setup(filename){const db=new SQLiteD1(filename);db.migrate();db.db.prepare('INSERT INTO users(id,created_at) VALUES(?,?)').run('user',1);return{db,ledger:new Ledger(db)};}
function quote(db,id,cad=3233,user='user'){db.db.prepare("INSERT INTO quotes(id,user_id,purchase_key,provider,source,cad_cents,gift_cents,fx_label,created_at,expires_at) VALUES(?,?,?,'Demo','entered',?,?,'test',1,9999999999)").run(id,user,id,cad,roundUp(cad));}
async function seed(db,ledger,count=8){for(let i=0;i<count;i++){quote(db,`q${i}`);await ledger.pledge('user',`q${i}`,2);}}
test('15-cent floor, exact whole totals, and integer FX arithmetic',()=>{
  assert.equal(roundUp(cents('29.85')),15);assert.equal(roundUp(cents('29.99')),101);assert.equal(roundUp(cents('29.86')),114);assert.equal(roundUp(cents('30')),0);
  assert.equal(convertUSD(2240,'1.4246',250),3271);assert.throws(()=>cents('12.345'));assert.throws(()=>cents('-1'));assert.throws(()=>cents('1e4'));
});
test('repeated Yes on the same quote records one pledge',async()=>{const{db,ledger}=setup();quote(db,'q');await Promise.all(Array.from({length:10},()=>ledger.pledge('user','q',2)));assert.equal((await ledger.state('user')).pending_cents,67);assert.equal(db.db.prepare('SELECT COUNT(*) n FROM pledges').get().n,1);db.close();});
test('another account cannot approve or read this quote',async()=>{const{db,ledger}=setup();quote(db,'q');await assert.rejects(ledger.pledge('other','q',2));assert.equal((await ledger.state('user')).pending_cents,0);db.close();});
test('checkout is blocked below C$5',async()=>{const{db,ledger}=setup();await seed(db,ledger,7);await assert.rejects(ledger.reserve('user',3));assert.equal((await ledger.state('user')).pending_cents,469);db.close();});
test('simultaneous checkout requests reserve one set of pledges',async()=>{const{db,ledger}=setup();await seed(db,ledger);const rows=await Promise.all(Array.from({length:12},()=>ledger.reserve('user',3)));assert.equal(new Set(rows.map(x=>x.id)).size,1);assert.equal(rows[0].amount_cents,536);assert.equal(db.db.prepare('SELECT COUNT(*) n FROM checkouts').get().n,1);db.close();});
test('verified payment clears only reserved pledges; replay is harmless',async()=>{const{db,ledger}=setup();await seed(db,ledger);let c=await ledger.reserve('user',3);c=await ledger.attach(c,{id:'cs_test_one',url:'https://checkout.stripe.com/test'});quote(db,'new',2999);await ledger.pledge('user','new',4);await ledger.settle(c,5,'event-one');await ledger.settle(c,6,'event-one');const s=await ledger.state('user');assert.equal(s.pending_cents,101);assert.equal(s.paid_cents,536);assert.equal(s.active,null);assert.equal(db.db.prepare('SELECT COUNT(*) n FROM payment_events').get().n,1);db.close();});
test('a failed settlement rolls the whole batch back',async()=>{const{db,ledger}=setup();await seed(db,ledger);let c=await ledger.reserve('user',3);c=await ledger.attach(c,{id:'cs_test_bad',url:'https://checkout.stripe.com/test'});db.db.prepare('UPDATE checkouts SET amount_cents=999 WHERE id=?').run(c.id);await assert.rejects(ledger.settle(c,5,'bad-event'));assert.equal((await ledger.state('user')).pending_cents,536);assert.equal(db.db.prepare('SELECT status FROM checkouts').get().status,'open');assert.equal(db.db.prepare('SELECT COUNT(*) n FROM payment_events').get().n,0);db.close();});
test('verified expiration releases pledges without clearing them',async()=>{const{db,ledger}=setup();await seed(db,ledger);const c=await ledger.reserve('user',3);await ledger.expire(c);await ledger.expire(c);const s=await ledger.state('user');assert.equal(s.pending_cents,536);assert.equal(s.paid_cents,0);assert.equal(s.active,null);const next=await ledger.reserve('user',5);assert.notEqual(next.id,c.id);assert.equal(next.amount_cents,536);db.close();});
test('paid ledger rows cannot be reset or changed',async()=>{const{db,ledger}=setup();await seed(db,ledger);let c=await ledger.reserve('user',3);c=await ledger.attach(c,{id:'cs_test_immutable',url:'https://checkout.stripe.com/test'});await ledger.settle(c,4,'event');assert.throws(()=>db.db.prepare('UPDATE pledges SET paid_at=NULL').run());assert.throws(()=>db.db.prepare("UPDATE checkouts SET status='open'").run());db.close();});
test('durability across process-style close/reopen and a second connection',async()=>{const dir=mkdtempSync(`${tmpdir()}/spare-ledger-`),file=`${dir}/data.sqlite`;try{const{db,ledger}=setup(file);await seed(db,ledger);const c=await ledger.reserve('user',3);db.close();const reopened=new SQLiteD1(file);reopened.migrate();const second=new SQLiteD1(file);assert.equal((await new Ledger(reopened).state('user')).pending_cents,536);assert.equal((await new Ledger(second).reserve('user',4)).id,c.id);reopened.close();second.close();}finally{rmSync(dir,{recursive:true});}});
